//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPDQ_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhBa
    {
        public string MaNV { get; set; }
        public Nullable<int> SoMayLe { get; set; }
        public string Vitri { get; set; }
        public Nullable<int> LoaiDB { get; set; }
    }
}
