//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPDQ_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HPDQEntities : DbContext
    {
        public HPDQEntities()
            : base("name=HPDQEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<DangKy> DangKies { get; set; }
        public virtual DbSet<DanhBa> DanhBas { get; set; }
        public virtual DbSet<GioiTinh> GioiTinhs { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhanMem> PhanMems { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<QuyenDangNhap> QuyenDangNhaps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThaoTac> ThaoTacs { get; set; }
        public virtual DbSet<TinhTrang> TinhTrangs { get; set; }
        public virtual DbSet<TrangThai> TrangThais { get; set; }
        public virtual DbSet<Viev_NhanVien> Viev_NhanVien { get; set; }
    
        public virtual int Chucvu_delete(Nullable<int> maCV)
        {
            var maCVParameter = maCV.HasValue ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Chucvu_delete", maCVParameter);
        }
    
        public virtual int Chucvu_insert(string tenCV)
        {
            var tenCVParameter = tenCV != null ?
                new ObjectParameter("TenCV", tenCV) :
                new ObjectParameter("TenCV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Chucvu_insert", tenCVParameter);
        }
    
        public virtual int Chucvu_update(Nullable<int> maCV, string tenCV)
        {
            var maCVParameter = maCV.HasValue ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(int));
    
            var tenCVParameter = tenCV != null ?
                new ObjectParameter("TenCV", tenCV) :
                new ObjectParameter("TenCV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Chucvu_update", maCVParameter, tenCVParameter);
        }
    
        public virtual int Dangky_delete(string tenDangNhap)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Dangky_delete", tenDangNhapParameter);
        }
    
        public virtual int Dangky_insert(string tenDangNhap, string matKhau, string maNV, Nullable<int> maQuyen, Nullable<System.DateTime> ngayCap, Nullable<int> trangThai)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maQuyenParameter = maQuyen.HasValue ?
                new ObjectParameter("MaQuyen", maQuyen) :
                new ObjectParameter("MaQuyen", typeof(int));
    
            var ngayCapParameter = ngayCap.HasValue ?
                new ObjectParameter("NgayCap", ngayCap) :
                new ObjectParameter("NgayCap", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Dangky_insert", tenDangNhapParameter, matKhauParameter, maNVParameter, maQuyenParameter, ngayCapParameter, trangThaiParameter);
        }
    
        public virtual int Dangky_update(string tenDangNhap, string maNV, Nullable<int> maQuyen, Nullable<System.DateTime> ngayCap, Nullable<int> trangThai)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maQuyenParameter = maQuyen.HasValue ?
                new ObjectParameter("MaQuyen", maQuyen) :
                new ObjectParameter("MaQuyen", typeof(int));
    
            var ngayCapParameter = ngayCap.HasValue ?
                new ObjectParameter("NgayCap", ngayCap) :
                new ObjectParameter("NgayCap", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Dangky_update", tenDangNhapParameter, maNVParameter, maQuyenParameter, ngayCapParameter, trangThaiParameter);
        }
    
        public virtual int Dangky_update_password(string tenDangNhap, string matKhau)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Dangky_update_password", tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual int Menu_delete(Nullable<int> maMenu)
        {
            var maMenuParameter = maMenu.HasValue ?
                new ObjectParameter("MaMenu", maMenu) :
                new ObjectParameter("MaMenu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Menu_delete", maMenuParameter);
        }
    
        public virtual int Menu_insert(string tenMenu, string lienKet, Nullable<int> maMenuCha, Nullable<int> thuTu, Nullable<int> trangThai)
        {
            var tenMenuParameter = tenMenu != null ?
                new ObjectParameter("TenMenu", tenMenu) :
                new ObjectParameter("TenMenu", typeof(string));
    
            var lienKetParameter = lienKet != null ?
                new ObjectParameter("LienKet", lienKet) :
                new ObjectParameter("LienKet", typeof(string));
    
            var maMenuChaParameter = maMenuCha.HasValue ?
                new ObjectParameter("MaMenuCha", maMenuCha) :
                new ObjectParameter("MaMenuCha", typeof(int));
    
            var thuTuParameter = thuTu.HasValue ?
                new ObjectParameter("ThuTu", thuTu) :
                new ObjectParameter("ThuTu", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Menu_insert", tenMenuParameter, lienKetParameter, maMenuChaParameter, thuTuParameter, trangThaiParameter);
        }
    
        public virtual int Menu_update(Nullable<int> maMenu, string tenMenu, string lienKet, Nullable<int> maMenuCha, Nullable<int> thuTu, Nullable<int> trangThai)
        {
            var maMenuParameter = maMenu.HasValue ?
                new ObjectParameter("MaMenu", maMenu) :
                new ObjectParameter("MaMenu", typeof(int));
    
            var tenMenuParameter = tenMenu != null ?
                new ObjectParameter("TenMenu", tenMenu) :
                new ObjectParameter("TenMenu", typeof(string));
    
            var lienKetParameter = lienKet != null ?
                new ObjectParameter("LienKet", lienKet) :
                new ObjectParameter("LienKet", typeof(string));
    
            var maMenuChaParameter = maMenuCha.HasValue ?
                new ObjectParameter("MaMenuCha", maMenuCha) :
                new ObjectParameter("MaMenuCha", typeof(int));
    
            var thuTuParameter = thuTu.HasValue ?
                new ObjectParameter("ThuTu", thuTu) :
                new ObjectParameter("ThuTu", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Menu_update", maMenuParameter, tenMenuParameter, lienKetParameter, maMenuChaParameter, thuTuParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<Nhanvien_danhsach_Result> Nhanvien_danhsach(Nullable<int> maPB)
        {
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nhanvien_danhsach_Result>("Nhanvien_danhsach", maPBParameter);
        }
    
        public virtual int Nhanvien_delete(Nullable<int> iDNV)
        {
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nhanvien_delete", iDNVParameter);
        }
    
        public virtual ObjectResult<Nhanvien_DO_Result> Nhanvien_DO(Nullable<int> iDNV)
        {
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nhanvien_DO_Result>("Nhanvien_DO", iDNVParameter);
        }
    
        public virtual ObjectResult<Nhanvien_DO_DanhBa_Result> Nhanvien_DO_DanhBa(Nullable<int> iDNV)
        {
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nhanvien_DO_DanhBa_Result>("Nhanvien_DO_DanhBa", iDNVParameter);
        }
    
        public virtual int Nhanvien_insert(string maNV, string tenNV, Nullable<int> maCV, Nullable<int> maPB, string diaChi, string sDT, Nullable<int> gioiTinh, string email, Nullable<System.DateTime> ngayVaoLam, Nullable<int> trangThai)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var maCVParameter = maCV.HasValue ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(int));
    
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var ngayVaoLamParameter = ngayVaoLam.HasValue ?
                new ObjectParameter("NgayVaoLam", ngayVaoLam) :
                new ObjectParameter("NgayVaoLam", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nhanvien_insert", maNVParameter, tenNVParameter, maCVParameter, maPBParameter, diaChiParameter, sDTParameter, gioiTinhParameter, emailParameter, ngayVaoLamParameter, trangThaiParameter);
        }
    
        public virtual int Nhanvien_insert_API(string maNV, string tenNV, Nullable<int> maCV, Nullable<int> maPB, Nullable<int> gioiTinh, Nullable<int> trangThai, string sDT)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var maCVParameter = maCV.HasValue ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(int));
    
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nhanvien_insert_API", maNVParameter, tenNVParameter, maCVParameter, maPBParameter, gioiTinhParameter, trangThaiParameter, sDTParameter);
        }
    
        public virtual int Nhanvien_insert_danhba(string maNV, string tenNV, Nullable<int> maCV, Nullable<int> maPB, Nullable<int> maGT)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var maCVParameter = maCV.HasValue ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(int));
    
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            var maGTParameter = maGT.HasValue ?
                new ObjectParameter("MaGT", maGT) :
                new ObjectParameter("MaGT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nhanvien_insert_danhba", maNVParameter, tenNVParameter, maCVParameter, maPBParameter, maGTParameter);
        }
    
        public virtual int Nhanvien_insert_Import(string maNV, string tenNV, Nullable<int> maCV, Nullable<int> maPB, Nullable<int> gioiTinh, Nullable<System.DateTime> ngayVaoLam, Nullable<int> trangThai)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var maCVParameter = maCV.HasValue ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(int));
    
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(int));
    
            var ngayVaoLamParameter = ngayVaoLam.HasValue ?
                new ObjectParameter("NgayVaoLam", ngayVaoLam) :
                new ObjectParameter("NgayVaoLam", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nhanvien_insert_Import", maNVParameter, tenNVParameter, maCVParameter, maPBParameter, gioiTinhParameter, ngayVaoLamParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<Nhanvien_search_Result> Nhanvien_search(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nhanvien_search_Result>("Nhanvien_search", searchParameter);
        }
    
        public virtual ObjectResult<Nhanvien_search_danhba_Result> Nhanvien_search_danhba(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nhanvien_search_danhba_Result>("Nhanvien_search_danhba", searchParameter);
        }
    
        public virtual int Nhanvien_update(Nullable<int> iDNV, string tenNV, Nullable<int> maCV, Nullable<int> maPB, string diaChi, string sDT, Nullable<int> maGT, string email, Nullable<System.DateTime> ngayVaoLam)
        {
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var maCVParameter = maCV.HasValue ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(int));
    
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var maGTParameter = maGT.HasValue ?
                new ObjectParameter("MaGT", maGT) :
                new ObjectParameter("MaGT", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var ngayVaoLamParameter = ngayVaoLam.HasValue ?
                new ObjectParameter("NgayVaoLam", ngayVaoLam) :
                new ObjectParameter("NgayVaoLam", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nhanvien_update", iDNVParameter, tenNVParameter, maCVParameter, maPBParameter, diaChiParameter, sDTParameter, maGTParameter, emailParameter, ngayVaoLamParameter);
        }
    
        public virtual int Nhanvien_update_API(string maNV, Nullable<int> maPB, string sDT)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nhanvien_update_API", maNVParameter, maPBParameter, sDTParameter);
        }
    
        public virtual int Nhanvien_update_danhba(string maNV, Nullable<int> soMayLe, string vitri, Nullable<int> loaiDB, Nullable<int> act)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var soMayLeParameter = soMayLe.HasValue ?
                new ObjectParameter("SoMayLe", soMayLe) :
                new ObjectParameter("SoMayLe", typeof(int));
    
            var vitriParameter = vitri != null ?
                new ObjectParameter("Vitri", vitri) :
                new ObjectParameter("Vitri", typeof(string));
    
            var loaiDBParameter = loaiDB.HasValue ?
                new ObjectParameter("LoaiDB", loaiDB) :
                new ObjectParameter("LoaiDB", typeof(int));
    
            var actParameter = act.HasValue ?
                new ObjectParameter("act", act) :
                new ObjectParameter("act", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nhanvien_update_danhba", maNVParameter, soMayLeParameter, vitriParameter, loaiDBParameter, actParameter);
        }
    
        public virtual int Nhanvien_update_Email(string maNV, string email)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nhanvien_update_Email", maNVParameter, emailParameter);
        }
    
        public virtual int Nhanvien_update_import(string maNV, Nullable<int> maCV, Nullable<int> maPB)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maCVParameter = maCV.HasValue ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(int));
    
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nhanvien_update_import", maNVParameter, maCVParameter, maPBParameter);
        }
    
        public virtual int Phanmem_delete(Nullable<int> maPM)
        {
            var maPMParameter = maPM.HasValue ?
                new ObjectParameter("MaPM", maPM) :
                new ObjectParameter("MaPM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Phanmem_delete", maPMParameter);
        }
    
        public virtual int Phanmem_insert(string tenPM)
        {
            var tenPMParameter = tenPM != null ?
                new ObjectParameter("TenPM", tenPM) :
                new ObjectParameter("TenPM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Phanmem_insert", tenPMParameter);
        }
    
        public virtual int Phanmem_update(Nullable<int> maPM, string tenPM)
        {
            var maPMParameter = maPM.HasValue ?
                new ObjectParameter("MaPM", maPM) :
                new ObjectParameter("MaPM", typeof(int));
    
            var tenPMParameter = tenPM != null ?
                new ObjectParameter("TenPM", tenPM) :
                new ObjectParameter("TenPM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Phanmem_update", maPMParameter, tenPMParameter);
        }
    
        public virtual int Phanquyen_delete(string tenDangNhap, Nullable<int> maMenu, Nullable<int> maTT)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var maMenuParameter = maMenu.HasValue ?
                new ObjectParameter("MaMenu", maMenu) :
                new ObjectParameter("MaMenu", typeof(int));
    
            var maTTParameter = maTT.HasValue ?
                new ObjectParameter("MaTT", maTT) :
                new ObjectParameter("MaTT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Phanquyen_delete", tenDangNhapParameter, maMenuParameter, maTTParameter);
        }
    
        public virtual int Phanquyen_insert(string tenDangNhap, Nullable<int> maMenu, Nullable<int> maTT, Nullable<int> giaTri)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var maMenuParameter = maMenu.HasValue ?
                new ObjectParameter("MaMenu", maMenu) :
                new ObjectParameter("MaMenu", typeof(int));
    
            var maTTParameter = maTT.HasValue ?
                new ObjectParameter("MaTT", maTT) :
                new ObjectParameter("MaTT", typeof(int));
    
            var giaTriParameter = giaTri.HasValue ?
                new ObjectParameter("GiaTri", giaTri) :
                new ObjectParameter("GiaTri", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Phanquyen_insert", tenDangNhapParameter, maMenuParameter, maTTParameter, giaTriParameter);
        }
    
        public virtual int Phanquyen_update(string tenDangNhap, Nullable<int> maMenu, Nullable<int> maTT, Nullable<int> giaTri)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var maMenuParameter = maMenu.HasValue ?
                new ObjectParameter("MaMenu", maMenu) :
                new ObjectParameter("MaMenu", typeof(int));
    
            var maTTParameter = maTT.HasValue ?
                new ObjectParameter("MaTT", maTT) :
                new ObjectParameter("MaTT", typeof(int));
    
            var giaTriParameter = giaTri.HasValue ?
                new ObjectParameter("GiaTri", giaTri) :
                new ObjectParameter("GiaTri", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Phanquyen_update", tenDangNhapParameter, maMenuParameter, maTTParameter, giaTriParameter);
        }
    
        public virtual int Phongban_delete(Nullable<int> maPB)
        {
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Phongban_delete", maPBParameter);
        }
    
        public virtual int Phongban_insert(string tenPB)
        {
            var tenPBParameter = tenPB != null ?
                new ObjectParameter("TenPB", tenPB) :
                new ObjectParameter("TenPB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Phongban_insert", tenPBParameter);
        }
    
        public virtual int Phongban_update(Nullable<int> maPB, string tenPB)
        {
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            var tenPBParameter = tenPB != null ?
                new ObjectParameter("TenPB", tenPB) :
                new ObjectParameter("TenPB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Phongban_update", maPBParameter, tenPBParameter);
        }
    
        public virtual int Quyendangnhap_delete(Nullable<int> maQuyen)
        {
            var maQuyenParameter = maQuyen.HasValue ?
                new ObjectParameter("MaQuyen", maQuyen) :
                new ObjectParameter("MaQuyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Quyendangnhap_delete", maQuyenParameter);
        }
    
        public virtual int Quyendangnhap_insert(string tenQuyen)
        {
            var tenQuyenParameter = tenQuyen != null ?
                new ObjectParameter("TenQuyen", tenQuyen) :
                new ObjectParameter("TenQuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Quyendangnhap_insert", tenQuyenParameter);
        }
    
        public virtual int Quyendangnhap_update(Nullable<int> maQuyen, string tenQuyen)
        {
            var maQuyenParameter = maQuyen.HasValue ?
                new ObjectParameter("MaQuyen", maQuyen) :
                new ObjectParameter("MaQuyen", typeof(int));
    
            var tenQuyenParameter = tenQuyen != null ?
                new ObjectParameter("TenQuyen", tenQuyen) :
                new ObjectParameter("TenQuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Quyendangnhap_update", maQuyenParameter, tenQuyenParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Taikhoan_danhsach_Result> Taikhoan_danhsach(Nullable<int> maPB, Nullable<int> maPM, string search)
        {
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            var maPMParameter = maPM.HasValue ?
                new ObjectParameter("MaPM", maPM) :
                new ObjectParameter("MaPM", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Taikhoan_danhsach_Result>("Taikhoan_danhsach", maPBParameter, maPMParameter, searchParameter);
        }
    
        public virtual int Taikhoan_delete(Nullable<int> tKID)
        {
            var tKIDParameter = tKID.HasValue ?
                new ObjectParameter("TKID", tKID) :
                new ObjectParameter("TKID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Taikhoan_delete", tKIDParameter);
        }
    
        public virtual int Taikhoan_delete_MaNV(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Taikhoan_delete_MaNV", maNVParameter);
        }
    
        public virtual int Taikhoan_insert(string maNV, Nullable<int> maPM, string tenTK, Nullable<System.DateTime> ngayCap, Nullable<int> trangThai, string ghiChu, Nullable<int> maTinhTrang)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maPMParameter = maPM.HasValue ?
                new ObjectParameter("MaPM", maPM) :
                new ObjectParameter("MaPM", typeof(int));
    
            var tenTKParameter = tenTK != null ?
                new ObjectParameter("TenTK", tenTK) :
                new ObjectParameter("TenTK", typeof(string));
    
            var ngayCapParameter = ngayCap.HasValue ?
                new ObjectParameter("NgayCap", ngayCap) :
                new ObjectParameter("NgayCap", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var maTinhTrangParameter = maTinhTrang.HasValue ?
                new ObjectParameter("MaTinhTrang", maTinhTrang) :
                new ObjectParameter("MaTinhTrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Taikhoan_insert", maNVParameter, maPMParameter, tenTKParameter, ngayCapParameter, trangThaiParameter, ghiChuParameter, maTinhTrangParameter);
        }
    
        public virtual int Taikhoan_lock(Nullable<int> tKID)
        {
            var tKIDParameter = tKID.HasValue ?
                new ObjectParameter("TKID", tKID) :
                new ObjectParameter("TKID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Taikhoan_lock", tKIDParameter);
        }
    
        public virtual int Taikhoan_unlock(Nullable<int> tKID)
        {
            var tKIDParameter = tKID.HasValue ?
                new ObjectParameter("TKID", tKID) :
                new ObjectParameter("TKID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Taikhoan_unlock", tKIDParameter);
        }
    
        public virtual int Taikhoan_update(Nullable<int> tKID, Nullable<System.DateTime> ngayCap, Nullable<int> trangThai, string ghiChu, Nullable<int> maTinhTrang)
        {
            var tKIDParameter = tKID.HasValue ?
                new ObjectParameter("TKID", tKID) :
                new ObjectParameter("TKID", typeof(int));
    
            var ngayCapParameter = ngayCap.HasValue ?
                new ObjectParameter("NgayCap", ngayCap) :
                new ObjectParameter("NgayCap", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var maTinhTrangParameter = maTinhTrang.HasValue ?
                new ObjectParameter("MaTinhTrang", maTinhTrang) :
                new ObjectParameter("MaTinhTrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Taikhoan_update", tKIDParameter, ngayCapParameter, trangThaiParameter, ghiChuParameter, maTinhTrangParameter);
        }
    
        public virtual int Thaotac_delete(Nullable<int> maTT)
        {
            var maTTParameter = maTT.HasValue ?
                new ObjectParameter("MaTT", maTT) :
                new ObjectParameter("MaTT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Thaotac_delete", maTTParameter);
        }
    
        public virtual int Thaotac_insert(string tenTT)
        {
            var tenTTParameter = tenTT != null ?
                new ObjectParameter("TenTT", tenTT) :
                new ObjectParameter("TenTT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Thaotac_insert", tenTTParameter);
        }
    
        public virtual int Thaotac_update(Nullable<int> maTT, string tenTT)
        {
            var maTTParameter = maTT.HasValue ?
                new ObjectParameter("MaTT", maTT) :
                new ObjectParameter("MaTT", typeof(int));
    
            var tenTTParameter = tenTT != null ?
                new ObjectParameter("TenTT", tenTT) :
                new ObjectParameter("TenTT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Thaotac_update", maTTParameter, tenTTParameter);
        }
    
        public virtual ObjectResult<thongtin_danhba_Result> thongtin_danhba(Nullable<int> maPB)
        {
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongtin_danhba_Result>("thongtin_danhba", maPBParameter);
        }
    
        public virtual ObjectResult<thongtin_danhba_DC_Result> thongtin_danhba_DC(Nullable<int> maPB)
        {
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongtin_danhba_DC_Result>("thongtin_danhba_DC", maPBParameter);
        }
    
        public virtual ObjectResult<thongtin_danhba_NV_Result> thongtin_danhba_NV(Nullable<int> maPB, string search)
        {
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongtin_danhba_NV_Result>("thongtin_danhba_NV", maPBParameter, searchParameter);
        }
    
        public virtual ObjectResult<thongtin_taikhoan_Result> thongtin_taikhoan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongtin_taikhoan_Result>("thongtin_taikhoan");
        }
    }
}
