//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPDQ_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int MaMenu { get; set; }
        public string TenMenu { get; set; }
        public string LienKet { get; set; }
        public Nullable<int> MaMenuCha { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Icon { get; set; }
    }
}
