//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPDQ_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int TKID { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> MaPM { get; set; }
        public string TenTK { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaTinhTrang { get; set; }
    
        public virtual PhanMem PhanMem { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
    }
}
