//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPDQ_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viev_NhanVien
    {
        public int IDNV { get; set; }
        public Nullable<int> MaCV { get; set; }
        public Nullable<int> MaPB { get; set; }
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public string Ho_Ten { get; set; }
        public string TenCV { get; set; }
        public string TenPB { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
    }
}
